on:
  github:
    branches:
      only: main

jobs:
  TrainModel:
    resources:
      instance-type: C3
    uses: container@v1
    with:
      args:
        - bash
        - -c
        - >-
          env | grep -i PROJECT
      image: bash
